### ISSUE TITLE
Rules for contributing in the open source project (for beginners)

### ISSUE THREAD

**Issue by WaderManasi** [kothariji/SyntaxMeets#29]
Adding detailed steps regarding **Contribution to Open Source Projects :  AS A BEGINNER** in contributing.md file would help the newbies to  get acquainted with the rules of contributing in open source projects.

**Comment by WaderManasi** [comment]
@kothariji if it is valid,
I would like to work on the mentioned issue.

**Comment by kothariji** [comment]
> Adding detailed steps regarding *Contribution to Open Source Projects : AS A BEGINNER* in contributing.md file would help the newbies to get acquainted with the rules of contributing in open source projects.

I agree with your point. One should get a complete guide from cloning the repo, to working on a branch and then finally generating a PR. 
Please go forward to work on CONTRIBUTING.md. I am assigning this issue to you👍. 

Few things you can add
1. You can mention the [ISSUE_TEMPALTES](https://github.com/kothariji/SyntaxMeets/tree/master/.github/ISSUE_TEMPLATE) for [BUG_REPORT](https://github.com/kothariji/SyntaxMeets/blob/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md) and [FEATURE REQUEST](https://github.com/kothariji/SyntaxMeets/blob/master/.github/ISSUE_TEMPLATE/FEATURE_REQUEST.md) so that contributors can get to know about how to create an issue in a systematic manner.
2.  Though I have mentioned in the Readme.md, Please add the below section, otherwise the application won't run on their local machines
```
create a new .env file in the frontend/syntaxmeets folder and add the following variables

REACT_APP_SYNTAXMEETS_BACKEND_API = 'http://localhost:4000/'
REACT_APP_ONLINE_JUDGE_API = YOUR API KEY
```
3. Rest open to endless possibilities. 💯 😊

And last but not least
Keep Contributing 🔥
