### ISSUE TITLE
Validation, Alert issues in Create and Join Room

### ISSUE THREAD

**Issue by AmeyaJain-25** [kothariji/SyntaxMeets#48]
**Describe the bug**
While creating a room, when we submit the input with empty characters, it gives and default browser alert. But after clicking on "ok" of alert, the popup or Modal get's disappeared.
Same with the Join room. In join room, if name is empty and the room id is wrong, then it continuously checks and gives two alert one back to the other. 

I will rectify this error and also I will try to give an different ALERT other than the default browser error.

**To Reproduce**
Clear steps describing how to reproduce the issue.
1. Go to 'Home Page'
2. Click on 'Create Room'
3. Click on 'Create Room button with empty input'
4. Accept the alert.
5. See the error

**Expected result**
The validation should be proper and Modal shouldn't go after accepting the alert.

**Actual result**
Modal got disabled after accepting the alert.

**Screenshots**

**Are you willing to contribute to this issue?** [Yes/No]
Yes

**Additional context**
I would like to solve this issue as being a participant of GSSoC 21'. Please assign me this issue.
Also, I would do the validation proper with an different Alert message or pop-up or notifications.

**Comment by kothariji** [comment]
Hi @AmeyaJain-25, First of all, thank you so much for taking out the time to create this issue.

Yeah, I think it's a clever idea to use some customizable modals instead of dull browser alerts.
Also, please try to maintain the [color theme of the project](https://coolors.co/000a29-0077b6-00b4d8-ffd500-f3f7f7-ffffff)
Definitely 🙌, Please go forward to work on this issue. I am assigning this Issue to you 👍


And last but not least,
Keep Contributing 🙏🔥

**Comment by AmeyaJain-25** [comment]
Issue is resolved. Ready to make PR

While resolving issue, package.lock.json is created. So, should I delete this file and then make a PR or it's okay with the package.lock.json file

**Comment by kothariji** [comment]
Thank you for your contributions @AmeyaJain-25 🚀 

Keep Contributing 🙏 🔥
