### ISSUE TITLE
[Feat]: Adding Lazy Loading component for improving performance of application.

### ISSUE THREAD

**Issue by WaderManasi** [kothariji/SyntaxMeets#79]
**Describe the solution you'd like**
- We can render the components only when the user requests for it.
(initial loading time will get reduced)
- React Loader can be added.

**Are you willing to contribute to this issue?** [Yes/No]
Yes, being part of gssoc'21

**Comment by Vishv07** [comment]
As of now, we have very few components, what I mean by that is we have the main panel is room. so anyway the moment the user step into the room, all components has to be loaded. so it's doable but I think it won't reduce the loading time as such.

Since vercel is very quick and our landing page isn't taking much time but still Lazy Loading can be done after all its your call @kothariji

**Comment by kothariji** [comment]
Hi @WaderManasi, First of all, thank you so much for taking out the time to create this issue.

Oh Yes, actually I analyzed the initial loading time of Sytaxmeets, and on the initial render, all the components are imported(**this is the normal behavior, as we write import statements directly**).

### And this is affecting the performance of our application.
![image](https://user-images.githubusercontent.com/60866749/111421502-1d432480-8713-11eb-8cb8-0904eeb5077a.png)

So for now we can use Lazy( ) in App.js for React-Routers so that SyntaxRooms is only called when someone joins the room.

So @Vishv07, I think we are good to go with the lazy import of big components, which will improve performance.
What say @Vishv07 ?

Definitely 🙌, Please go forward to work on this issue. I am assigning this Issue to you 👍

And last but not least,
Keep Contributing 🙏🔥

**Comment by Vishv07** [comment]
@kothariji Yes, we can reduce the initial loading time. let @WaderManasi give it a shot and then we will compare it.

**Comment by kothariji** [comment]
# Old Performance
![image](https://user-images.githubusercontent.com/60866749/111516840-65496200-877a-11eb-9658-eadb44033999.png)

# New Performance
![image](https://user-images.githubusercontent.com/60866749/111517017-9c1f7800-877a-11eb-9578-f6aa40301d21.png)

Great Work @WaderManasi 🙌 

thank you so much for your contributions 🔥

**Comment by WaderManasi** [comment]
Thank you 🙌!
